### Задание
Имеются данные adult.csv (см. в материалах к занятию).
Целевой переменной является уровень дохода income (крайний правый столбец).
Описание признаков можно найти по ссылке www.cs.toronto.edu...etail.html

Вам необходимо построить модели логистической регрессии и SVM, которые предсказывает уровень дохода человека.
Вывести качество полученных моделей на тестовой выборке, используя функцию score у модели.

In [1]:
import numpy as np
import pandas as pd
import scipy.stats 
import matplotlib.pyplot as plt  

In [2]:
data = pd.read_csv('adult.csv')
data.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18          ?  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [3]:
incomes = data['income']
incomes.unique()

array(['<=50K', '>50K'], dtype=object)

In [30]:
ad_income = data[['age', 'educational-num','income']]
ad_income

age  educational-num income
0       25                7  <=50K
1       38                9  <=50K
2       28               12   >50K
3       44               10   >50K
4       18               10  <=50K
...    ...              ...    ...
48837   27               12  <=50K
48838   40                9   >50K
48839   58                9  <=50K
48840   22                9  <=50K
48841   52                9   >50K

[48842 rows x 3 columns]

In [31]:
ad_income.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              48842 non-null  int64 
 1   educational-num  48842 non-null  int64 
 2   income           48842 non-null  object
dtypes: int64(2), object(1)
memory usage: 1.1+ MB


In [32]:
ad_income.describe()

age  educational-num
count  48842.000000     48842.000000
mean      38.643585        10.078089
std       13.710510         2.570973
min       17.000000         1.000000
25%       28.000000         9.000000
50%       37.000000        10.000000
75%       48.000000        12.000000
max       90.000000        16.000000

###### построить модели логистической регрессии и SVM, которые предсказывает уровень дохода человека.

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [34]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [35]:
X = ad_income.apply(LabelEncoder().fit_transform)

In [36]:

X.head()

age  educational-num  income
0    8                6       0
1   21                8       0
2   11               11       1
3   27                9       1
4    1                9       0

In [37]:
le.fit(ad_income['income'])

LabelEncoder()

In [38]:
le.classes_

array(['<=50K', '>50K'], dtype=object)

In [39]:
le.transform( ['<=50K', '>50K', '<=50K'])

array([0, 1, 0])

In [40]:
from sklearn.pipeline import make_pipeline # используем пайплайны для удобства
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split 

model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=100000))

In [41]:
model

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression(max_iter=100000))])

In [42]:
y = pd.Series (data = le.transform(data['income']))
y.head()

0    0
1    0
2    1
3    1
4    0
dtype: int32

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [51]:
model.fit(X_train, y_train)
predictions = model.predict(X_test)

In [52]:
predictions[:10]

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0])

In [53]:
model.predict(X_test)

array([0, 0, 1, ..., 1, 0, 1])

In [54]:
model.predict_proba(X_test)

array([[9.99872775e-01, 1.27225152e-04],
       [9.99932642e-01, 6.73580056e-05],
       [2.51916399e-04, 9.99748084e-01],
       ...,
       [3.64407605e-04, 9.99635592e-01],
       [9.99956742e-01, 4.32577817e-05],
       [2.09452214e-04, 9.99790548e-01]])

In [55]:
model.score(X_train, y_train) 

1.0

In [56]:
model.score(X_test,y_test)

1.0

##### SVC

In [57]:
from sklearn.svm import SVC
# используем пайплайны
clf = make_pipeline(StandardScaler(), SVC(gamma='auto')) 
clf.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [58]:
clf.score(X_train, y_train) 

1.0

In [59]:
clf.score(X_test, y_test)

1.0

In [60]:
svc = SVC(gamma='auto')
svc.fit(X_train, y_train)

SVC(gamma='auto')

In [61]:
svc.score(X_train, y_train)

0.999872034397154

In [62]:
svc.score(X_test, y_test)

0.999181083017709